### PR TITLE
surface (fix): Fixes #3418 Handle surface of List of generic tuples

### LINKED ISSUE #3418: Surface.of fails with error for a class containing generic list of tuples in Scala 3
airframe-surface ver. 24.2.2, Scala 3.3.2, 3.4.1-RC1

List of tuples fails with error:

```scala
import wvlet.airframe.surface.Surface

object Main {
  case class A[P](data: List[(String, P)])

  case class S(alarms: A[Int])

  Surface.of[S]

  def main(args: Array[String]): Unit = {

  }
}
```

Error is:

> Found:    (x.data : List[(String, Int)])
> Required: List[(String, P)]

It seems type is not applied.

### PR DESCRIPTION
**Pull request by OndrejSpanel**
Again starting with the test, passing in Scala 2

Let us see if I will be able to fix it, this time I am not yet sure where to start.

### CODE REVIEW

**Comment by OndrejSpanel** [comment]
Logging output, with added logging of `resolvedTypeArgs` and few other expressions:

```
==== method args of wvlet.airframe.surface.i3418.A[Int]
=== val data: scala.List[scala.Tuple2[scala.Predef.String, P]] Flags.Param false
===  a.args List(AppliedType(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Tuple2),List(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class scala)),object Predef),type String), TypeRef(NoPrefix,type P))))
===  typeArgTable Map(P -> TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object scala),class Int))
===  resolvedTypeArgs List(AppliedType(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Tuple2),List(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class scala)),object Predef),type String), TypeRef(NoPrefix,type P))))```

The types need to be resolved recursively, so that type parameters are replaced even in inner types.

**Comment by OndrejSpanel** [comment]
Working in the surface sources is a pleasure - it well structured and logical. I hope my contributions are able to maintain the level.

I would use scalafmt to fix the formatting, however I have no idea how to and I do not see from the output what exactly did in wrong in my formatting.

**Comment by xerial** [comment]
Thanks for the recent report and contributions! I'll take a look. 

Here are some tips for writing Scala 3 macros; I often check Dotty's source code https://github.com/lampepfl/dotty/blob/main/library/src/scala/quoted/Quotes.scala and look at xxxMethods extensions to understand what methods are available.

**Comment by OndrejSpanel** [comment]
@xerial Thanks for reviewing and merging. Would it be possible to publish the library with the current fixes, please?

I think all issues which were blocking my app port to Scala 3 should be resolved by now, other issues are non-blockers for me and can wait, but those until now made my app unusable (critical parts not compiling).

**Pull request merged**
