### PR TITLE
Disable coloring when using PlainSourceCodeLogFormatter

### PR DESCRIPTION
**Pull request by yuokada**

### CODE REVIEW

**Comment by xerial** [comment]
Thanks. By the way, what's the use case? 

Recently, almost all environment supports colored ANSI logs (e.g., less -R), removing ANSI color code with ansi2txt, etc.

**Comment by yuokada** [comment]
Planning to store non-colored logs into a file to send them using fluentd.

**Comment by xerial** [comment]
If that's the case, using a filter plugin like https://github.com/mattheworiordan/fluent-plugin-color-stripper might be useful :) We may still want to see colored logs in an emergency situation.

**Comment by yuokada** [comment]
That plugin doesn't work on `td-agent 4`.

**Pull request merged**
