### PR TITLE
Test scalafmt optIn.breaksInsideChains = true option

### PR DESCRIPTION
**Pull request by xerial**
Using https://github.com/scalameta/scalafmt/pull/1037 version

### CODE REVIEW

**Comment by xerial** [comment]
Temporary disabled sbt-microsite because it doesn't support sbt-1.0.0 https://github.com/47deg/sbt-microsites/pull/221

**Comment by xerial** [comment]
@Lewuathe 
- Added code format test task in TravisCI using a scalafmt binary. 
- Using a snapshot version of scalafmt-1.3.0 with `breaksInsideChains` option. Thanks @olafurpg for adding this!

**Comment by olafurpg** [comment]
Thanks for the ping @xerial Sorry about the slow release 😅

**Comment by xerial** [comment]
@olafurpg No problem! I'm now using 1.3.0. Thanks for the great plugin. I'm happy with this vesion.

**Comment by olafurpg** [comment]
Glad you like it 😄

**Pull request merged**
