### PR TITLE
[surface] Scala 3: Pass all tests on JVM

### PR DESCRIPTION
**Pull request by exoego**
It might be quick and dirty 😅 

# before

✅ 97

```
$ DOTTY=1 sbt surfaceJVM/test:clean;surfaceJVM/test ​

[error] Failed: Total 101, Failed 4, Errors 0, Passed 97
[error] Failed tests:
[error]         wvlet.airframe.surface.RecursiveSurfaceTest
[error]         wvlet.airframe.surface.RecursiveHigherKindTypeTest
[error]         wvlet.airframe.surface.reflect.RuntimeSurfaceTest
[error]         wvlet.airframe.surface.SurfaceTest
```

# after

✅ 101(+4)
```
[info] Passed: Total 101, Failed 0, Errors 0, Passed 101
```

### CODE REVIEW

**Review by xerial — APPROVED** [review]
Thanks for finding why higher-kinded types are not processed properly.

**Comment by xerial** [comment]
@exoego Note. Some tests `httpJVM/test` starts failing after this change. Currently, we are not running the full CI for Scala 3 as we still need many fixes, so finding the impact of the change to the other modules is a bit challenging. It might be better to add a CI test for projects whose migration has been completed (e.g., logJVM/test; controlJVM/test, surfaceJVM/test, ...) 

```
 - create a new sync client 1.06ms << error: key not found: wvlet.airframe.http.client.URLConnectionClientBase._.Resource

java.util.NoSuchElementException: key not found: wvlet.airframe.http.client.URLConnectionClientBase._.Resource
	at scala.collection.MapOps.default(Map.scala:274)
	at scala.collection.MapOps.default$(Map.scala:273)
	at scala.collection.AbstractMap.default(Map.scala:405)
	at scala.collection.MapOps.apply(Map.scala:176)
	at scala.collection.MapOps.apply$(Map.scala:175)
	at scala.collection.AbstractMap.apply(Map.scala:405)
	at wvlet.airframe.surface.package$.getCached(package.scala:11)
	at wvlet.airframe.surface.LazySurface.ref(Surfaces.scala:327)
	at wvlet.airframe.surface.LazySurface.typeArgs(Surfaces.scala:340)
	at wvlet.airframe.surface.Alias.<init>(Surfaces.scala:189)
	at wvlet.airframe.surface.Alias$.apply(Surfaces.scala:188)
```

**Comment by exoego** [comment]
https://github.com/wvlet/airframe/commit/c8173e5e99e42d34eb6e4d2fc8bae0b89271fe9f
```
logJVM/test
[info] Passed: Total 48, Failed 0, Errors 0, Passed 48
[success] Total time: 6 s, completed 4 Feb 2022, 13:40:55
```

```
[error] Error: Total 109, Failed 0, Errors 2, Passed 107, Pending 1
[error] Error during tests:
[error]         wvlet.airframe.codec.PrimitiveCodecTest
[error] (codecJVM / Test / test) sbt.TestsFailedException: Tests unsuccessful
```



```
[error] Error: Total 89, Failed 0, Errors 7, Passed 82, Pending 1
[error] Error during tests:
[error]         wvlet.airframe.di.PathDependentTypeTest
[error]         wvlet.airframe.di.ImplicitArgTest
[error]         wvlet.airframe.DesignSerializationTest
[error]         wvlet.airframe.ProviderSerializationTest
[error]         wvlet.airframe.DesignTest
[error] (diJVM / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 25 s, completed 4 Feb 2022, 13:39:29


```

#
codecJvm/test
[info] Passed: Total 109, Failed 0, Errors 0, Passed 109, Pending 1

**Comment by exoego** [comment]
That test was failing before change, just cache `key` is different
```
- create a new sync client 1.80ms << error: key not found: List(wvlet, airframe, http, client, URLConnectionClientBase, _.Resource)

java.util.NoSuchElementException: key not found: List(wvlet, airframe, http, client, URLConnectionClientBase, _.Resource)
        at scala.collection.MapOps.default(Map.scala:274)
        at scala.collection.MapOps.default$(Map.scala:273)
        at scala.collection.AbstractMap.default(Map.scala:405)
```

**Pull request merged**
