### PR TITLE
airframe-http: Support patch, patchOps, deleteOps methods

### PR DESCRIPTION
**Pull request by shimamoto**
refs #754

### CODE REVIEW

**Comment by xerial** [comment]
OK. LGTM. To pass code format check, run `sbt scalafmtAll`

**Comment by xerial** [comment]
If you are using IntelliJ, you can use `reformat on save` option https://www.jetbrains.com/help/idea/work-with-scala-formatter.html

**Comment by shimamoto** [comment]
I fixed the code format 😅

**Comment by xerial** [comment]
Merged. Congrats to your first PR to Airframe! A snapshot version will be available soon.

**Pull request merged**
