### PR TITLE
Add raw response methods to HttpClient

### PR DESCRIPTION
**Pull request by takezoe**
Add some convenient methods to `HttpClient` for handling a raw response.

### CODE REVIEW

**Comment by xerial** [comment]
@takezoe Please add test methods to make sure these methods are working as expected. Other than that, this PR is OK.

**Comment by takezoe** [comment]
Thanks for reviewing. I added tests.

In addition, `deleteOpsRaw` is also useful?
```scala
  def deleteOpsRaw[Resource: ru.TypeTag](
      resourcePath: String,
      resource: Resource,
      requestFilter: Req => Req = identity
  ): F[Resp]
```

**Comment by xerial** [comment]
For deleteOps, we can use `deleteOps[Resource, http.Response]`, so we don't need deleteOpsRaw

**Comment by xerial** [comment]
In this context, xxxRaw[Resource] methods will be just wrappers over `xxxOps[Resource, Response]`.

**Comment by xerial** [comment]
ok. LGTM.

**Pull request merged**
