### PR TITLE
Update snakeyaml to 1.18

### PR DESCRIPTION
**Pull request by 0x1997**

### CODE REVIEW

**Comment by xerial** [comment]
What's new about snakeyaml 1.18?

**Comment by 0x1997** [comment]
@xerial See https://bitbucket.org/asomov/snakeyaml/wiki/Changes

**Comment by xerial** [comment]
OK. Does this upgrade help anything for the problem like #110 or #109?

**Comment by 0x1997** [comment]
No. Currently `wvlet.surface` doesn't handle nested case classes or java beans properly.

**Pull request merged**
