### PR TITLE
airframe-arrow: Add ArrorFlight RPC interface

### PR DESCRIPTION
**Pull request by xerial**
ArrowFlight is using Protobuf for definign server/client. 
https://github.com/apache/arrow/blob/master/format/Flight.proto

This PR is an alternative interface of ArrowFlight without using any Protobuf. 
- FlightService server can be implemented in Scala using model classes. 
- FlightService client can be generated with sbt-airframe, which internally using MessagePack or JSON. If JSON is used, binary data need to be BASE64-encoded strings. 

Some learnings:
- ArrowFlights is using too many bytes array parameters. So the server/client developers still need some support for parsing byte array data.
- ArrowFlights is using client/server/bidi streaming a lot, but introducing pagenation might be better in terms of stability if it will be used for sending large volumes of data. 

discussion:
https://twitter.com/semanticbeeng/status/1432094625439887360

### CODE REVIEW

**Comment by SemanticBeeng** [comment]
> * server/client developers still need some support for parsing byte array data.

`Apache Arrow` is also implemented in JavaScript. https://arrow.apache.org/docs/js/
Could this be used in the generated bindings?

**Comment by SemanticBeeng** [comment]
> * ArrowFlights is using client/server/bidi streaming a lot, but introducing pagenation might be better in terms of stability if it will be used for sending large volumes of data.

`Apache Arrow` has this `RecordBatch`: https://gist.github.com/SemanticBeeng/0e9f9ed40866a5f844be13ab6ef3469e
I have the sense the `Arrow Flight` is using it behind the `gRPC` streaming.

Wondering how this could fit with `airframe`.

**Comment by xerial** [comment]
@SemanticBeeng If gRPC streaming is not used, sending data from server to browses can be supported if we launch Finagle (HTTP/1) backend. sbt-airframe already can generate JS client for RPC.

For doing so, we need to have different API, which doesn't require streaming (e.g., pagination-only)

**Comment by SemanticBeeng** [comment]
> If gRPC streaming is not used, sending data from server to browses can be supported if

So are you saying that `airframe-rpc` cannot support this https://github.com/wvlet/airframe/pull/1813#issuecomment-908722225 in `gRPC` binary streaming mode ?

I am somewhat aware of the limitations of `gRPC` in browsers but was left with the impression that this project is somehow improving on that. :thinking: 

If `gRPC` binary streaming mode cannot be supported with native `apache arrow` then indeed we can use a pagination based api using any of the backend frameworks.

Please advise @xerial

**Comment by xerial** [comment]
For using gRPC backend of grpc-java, we can implement Arrow-Flight like service in this PR using Airframe RPC, which supports all streaming modes of gRPC.

As there seems no active plan in gRPC and web browsers to support client-side streaming (e.g., Sending request parameters from a web browser to a server asynchronously), the current Arrow-flight RPC design cannot be used for supporting JavaScripts running at web browsers. Arrow Flight should have a version that has no client-side streaming and bidirectional streaming if we need web browser support.

**Comment by xerial** [comment]
gRPC and grpc-java are not suited to sending large volumes of byte data. For example, grpc-java uses just 4k for the gRPC message size. We can increase the limit, but sending large binary data is apparently not the central use cases of gRPC. 

I think the Apach Arrow protocol itself needs to be redesigned (e.g., creating non gRPC endpoint for sending binary data). I'll close this PR as supporting Apache Arrow with gRPC is not so promising at this moment.

**Pull request closed without merging**
